import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { WalletProvider } from '@/providers/WalletProvider';
import ThemeProvider from '@/providers/ThemeProvider';
import ReactQueryProvider from '@/providers/ReactQueryProvider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${inter.className} bg-purple-300/50 `}>
        <ReactQueryProvider>
          <WalletProvider>
            <ThemeProvider>{children}</ThemeProvider>
          </WalletProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
